"""Similar Wprds.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12KSHtKaAjubEnaBEU61M3yvOCWCUtIZS
"""

import gensim.downloader
word2vec = gensim.downloader.load('word2vec-google-news-300')

print(word2vec["13"])

print(word2vec.most_similar("monkey", topn=20))

print(word2vec.most_similar("dancing", topn=20))

print(word2vec.most_similar("mathematics", topn=20))

print(word2vec.most_similar("teacher"))

print(word2vec.most_similar("Metallica"))

print(word2vec.most_similar("Italy"))